### ISSUE TITLE
Automatic update synchronization

### ISSUE THREAD

**Issue by LosBagros** [c9679/Nightscout-Wemos-OLED#2]
Hello, sometimes my sensor lost connection and reconnect later than 5 minutes... And display stay with old data. It would be cool to automatically update when nightscout get new data.

If you want and you have free time please help me to get away BG text from the display - then will not be so small cgm value (it will be better to read)

Thank you wery much

**Comment by c9679** [comment]
The code is set to update every 5 minutes u can set it to update later or sooner, it used the pebble json from nightscout I havent looked into it enough it might be possible to modify the code to detect old readings not sure

**Comment by LosBagros** [comment]
OK
